import { Router } from "express";
import authRoutes from "./authRoutes.js";
import userRoutes from "./userRoutes.js";
import creatorRoutes from "./creatorRoutes.js";
import contentRoutes from "./contentRoutes.js";
import adminRoutes from "./adminRoutes.js";
import profileRoutes from "./profileRoutes.js";
import publicProfileRoutes from "./publicProfileRoutes.js";
import creatorVerificationRoutes from "./creatorVerificationRoutes.js";
import adminVerificationRoutes from "./adminVerificationRoutes.js";
import adminContentRoutes from "./adminContentRoutes.js";
import fanRoutes from "./fanRoutes.js";
import unifiedProfileRoutes from "./unifiedProfileRoutes.js";
import publicationRoutes from "./publicationRoutes.js";
import adminPublicationRoutes from "./adminPublicationRoutes.js";
import walletRoutes from "./walletRoutes.js";
import purchaseRoutes from "./purchaseRoutes.js";
import membershipRoutes,{premiumWorldRoutes} from "./membershipRoutes.js";
import adminFinancialRoutes from "./adminFinancialRoutes.js";
import wallRoutes from "./wallRoutes.js";
import storyRoutes from "./storyRoutes.js";
import { sendResponse } from "../utils/response.js";

const router = Router();

router.get("/health", (_req, res) => sendResponse(res, 200, "OnlyMe API is running"));
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/profile", profileRoutes);
router.use("/profiles", unifiedProfileRoutes);
router.use("/publications", publicationRoutes);
router.use("/wall", wallRoutes);
router.use("/stories", storyRoutes);
router.use("/",walletRoutes);
router.use("/worlds",purchaseRoutes);
router.use("/premium-worlds",premiumWorldRoutes);
router.use("/premium-memberships",membershipRoutes);
router.use("/", publicProfileRoutes);
router.use("/creator/verification", creatorVerificationRoutes);
router.use("/creator", creatorRoutes);
router.use("/content", contentRoutes);
router.use("/admin/creator-verifications", adminVerificationRoutes);
router.use("/admin/content-moderation", adminContentRoutes);
router.use("/admin/publication-moderation", adminPublicationRoutes);
router.use("/admin",adminFinancialRoutes);
router.use("/admin", adminRoutes);
router.use("/fan", fanRoutes);

export default router;

