import { Router } from "express";
import { createStory, deleteStory, getStory, listStories, reactStory, replyStory, viewStory } from "../controllers/storyController.js";
import { protect } from "../middleware/authMiddleware.js";
import { authorize } from "../middleware/roleMiddleware.js";
import { requireApprovedCreator } from "../middleware/creatorApprovalMiddleware.js";
import { uploadProfileImage } from "../middleware/uploadMiddleware.js";
import { requireMessagingAccess } from "../services/messagingAccessService.js";
const router = Router();
router.get("/active", protect, authorize("fan", "creator"), listStories);
router.get("/:id", protect, authorize("fan", "creator"), getStory);
router.post("/", protect, authorize("creator"), requireApprovedCreator, uploadProfileImage.single("image"), createStory);
router.post("/:id/views", protect, authorize("fan"), viewStory);
router.post("/:id/reactions", protect, authorize("fan"), requireMessagingAccess, reactStory);
router.post("/:id/replies", protect, authorize("fan"), requireMessagingAccess, replyStory);
router.delete("/:id", protect, authorize("creator"), deleteStory);
export default router;
