import { Router } from "express";
import { addWallComment, createWallPost, getWallComments, getWallReactions, listWallPosts, toggleWallReaction, toggleWallSave, toggleWallShare } from "../controllers/wallController.js";
import { optionalProtect, protect } from "../middleware/authMiddleware.js";
import { authorize } from "../middleware/roleMiddleware.js";
import { uploadProfileImage } from "../middleware/uploadMiddleware.js";
const router = Router();
router.get("/", optionalProtect, listWallPosts);
router.post("/", protect, authorize("fan", "creator"), uploadProfileImage.single("image"), createWallPost);
router.get("/:id/comments", optionalProtect, getWallComments);
router.get("/:id/reactions", optionalProtect, getWallReactions);
router.put("/:id/reaction", protect, authorize("fan", "creator"), toggleWallReaction);
router.post("/:id/comments", protect, authorize("fan", "creator"), addWallComment);
router.put("/:id/share", protect, authorize("fan", "creator"), toggleWallShare);
router.put("/:id/save", protect, authorize("fan", "creator"), toggleWallSave);
export default router;
