import crypto from "node:crypto";
import mongoose from "mongoose";
import Chapter from "../models/Chapter.js";
import Publication from "../models/Publication.js";
import PublicationReviewHistory from "../models/PublicationReviewHistory.js";
import { EDITABLE_PUBLICATION_STATUSES } from "../constants/publicationConstants.js";
import { assertCompletePublication, derivedPublicationPolicy, normalizeChapter, normalizePublicationDraft } from "../validators/publicationValidator.js";
import { verifyPublicationAsset } from "./publicationMediaStorageService.js";
import ApiError from "../utils/ApiError.js";
import { withTransactionFallback } from "./mongoTransactionService.js";

const history = async (publication, action, previousStatus, transitionId = crypto.randomUUID(), session = null) => { const [entry] = await PublicationReviewHistory.create([{ publication: publication._id, creator: publication.creator, action, previousStatus, newStatus: publication.status, revisionVersion: publication.draftVersion, transitionId }], session ? { session } : {}); return entry; };
const ensureId = (id) => { if (!mongoose.isValidObjectId(id)) throw new ApiError(400, "Invalid publication ID"); };
const editable = async (creatorId, id) => { ensureId(id); const publication = await Publication.findOne({ _id: id, creator: creatorId }).select("+submittedSnapshot"); if (!publication) throw new ApiError(404, "Publication not found"); if (!EDITABLE_PUBLICATION_STATUSES.includes(publication.status)) throw new ApiError(409, "Publication is not editable"); return publication; };
const expectedVersion = (payload) => { if (!Number.isSafeInteger(payload.statusVersion)) throw new ApiError(400, "statusVersion is required"); return payload.statusVersion; };
const metadataSnapshot = (publication) => ({ kind: publication.kind, title: publication.title, summary: publication.summary, description: publication.description, category: publication.category, tags: publication.tags, coverMedia: publication.coverMedia, introMedia: publication.introMedia, planet: publication.planet, pricing: publication.pricing, previewPolicy: publication.previewPolicy });
const chapterSnapshot = (chapter) => ({ stableChapterId: chapter.stableChapterId, order: chapter.order, title: chapter.title, blocks: chapter.blocks.map((block) => plain(block)), isPreview: chapter.isPreview, releaseMode: chapter.releaseMode, releaseAt: chapter.releaseAt, draftVersion: chapter.draftVersion });
const plain = (value) => typeof value?.toObject === "function" ? value.toObject() : value;

async function createWithSlot(creatorId, normalized, slot) { return withTransactionFallback(async (session) => { const policy = derivedPublicationPolicy(normalized.kind); const pricing = normalized.kind === "SEEN" ? policy.pricing : normalized.pricing; const [publication] = await Publication.create([{ creator: creatorId, ...normalized, pricing, previewPolicy: policy.previewPolicy, planet: normalized.kind === "SEEN" ? { slot: null } : { ...normalized.planet, slot }, status: "DRAFT" }], session ? { session } : {}); await history(publication, "DRAFT_CREATED", "DRAFT", crypto.randomUUID(), session); return publication; }); }
export async function createPublicationDraft(creatorId, payload) {
  const normalized = normalizePublicationDraft(payload); if (normalized.kind === "SEEN") return createWithSlot(creatorId, normalized, null);
  const slots = normalized.kind === "PREMIUM_WORLD" ? ["PREMIUM"] : ["WORLD_1", "WORLD_2"];
  for (const slot of slots) { try { return await createWithSlot(creatorId, normalized, slot); } catch (error) { if (error.code !== 11000) throw error; } }
  throw new ApiError(409, normalized.kind === "WORLD" ? "A creator may have at most two active Worlds" : "A creator may have at most one active Premium World");
}

export async function updatePublicationDraft(creatorId, id, payload) { const current = await editable(creatorId, id); const version = expectedVersion(payload); const normalized = normalizePublicationDraft(payload, { partial: true }); delete normalized.kind; if (normalized.planet) { normalized["planet.emoji"] = normalized.planet.emoji; normalized["planet.accent"] = normalized.planet.accent; delete normalized.planet; } const updated = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, status: current.status, statusVersion: version }, { $set: normalized, $inc: { statusVersion: 1, draftVersion: 1 } }, { new: true, runValidators: true }); if (!updated) throw new ApiError(409, "Publication changed while editing"); await history(updated, "DRAFT_UPDATED", current.status); return updated; }

async function trustedChapter(payload, context) { const normalized = normalizeChapter(payload); normalized.blocks = await Promise.all(normalized.blocks.map(async (block) => { if (!block.media) return block; return { ...block, media: await verifyPublicationAsset({ assetId: block.media.assetId, mediaType: block.type, blockId: block.id, ...context }) }; })); return normalized; }
export async function addChapter(creatorId, id, payload) { const publication = await editable(creatorId, id); const version = expectedVersion(payload); const stableChapterId = crypto.randomUUID(); const count = await Chapter.countDocuments({ publication: id }); if (count >= 10) throw new ApiError(409, "A publication may have at most ten chapters"); const chapter = await Chapter.create({ publication: id, stableChapterId, order: count, ...(await trustedChapter(payload, { creatorId, publicationId: id, chapterId: stableChapterId })) }); const updated = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, statusVersion: version, status: publication.status }, { $inc: { statusVersion: 1, draftVersion: 1 } }, { new: true }); if (!updated) { await Chapter.deleteOne({ _id: chapter._id }); throw new ApiError(409, "Publication changed while adding a chapter"); } await history(updated, "CHAPTER_ADDED", publication.status); return chapter; }
export async function updateChapter(creatorId, id, chapterId, payload) { const publication = await editable(creatorId, id); const version = expectedVersion(payload); const chapter = await Chapter.findOne({ publication: id, stableChapterId: chapterId }); if (!chapter) throw new ApiError(404, "Chapter not found"); const normalized = await trustedChapter(payload, { creatorId, publicationId: id, chapterId }); const updatedPublication = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, status: publication.status, statusVersion: version }, { $inc: { statusVersion: 1, draftVersion: 1 } }, { new: true }); if (!updatedPublication) throw new ApiError(409, "Publication changed while editing a chapter"); Object.assign(chapter, normalized); chapter.draftVersion += 1; await chapter.save(); await history(updatedPublication, "CHAPTER_UPDATED", publication.status); return chapter; }
export async function removeChapter(creatorId, id, chapterId, payload) { const publication = await editable(creatorId, id); const version = expectedVersion(payload); const chapter = await Chapter.findOne({ publication: id, stableChapterId: chapterId }); if (!chapter) throw new ApiError(404, "Chapter not found"); const updated = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, status: publication.status, statusVersion: version }, { $inc: { statusVersion: 1, draftVersion: 1 } }, { new: true }); if (!updated) throw new ApiError(409, "Publication changed while removing a chapter"); await Chapter.deleteOne({ _id: chapter._id }); const remaining = await Chapter.find({ publication: id }).sort({ order: 1 }); await Promise.all(remaining.map((item, order) => Chapter.updateOne({ _id: item._id }, { $set: { order } }))); await history(updated, "CHAPTER_REMOVED", publication.status); return updated; }
export async function reorderChapters(creatorId, id, payload) { const publication = await editable(creatorId, id); const version = expectedVersion(payload); if (!Array.isArray(payload.chapterIds)) throw new ApiError(400, "chapterIds is required"); const chapters = await Chapter.find({ publication: id }); const currentIds = chapters.map((item) => item.stableChapterId).sort(); if (payload.chapterIds.length !== currentIds.length || [...payload.chapterIds].sort().some((value, index) => value !== currentIds[index])) throw new ApiError(400, "Chapter order must contain every chapter exactly once"); const updated = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, status: publication.status, statusVersion: version }, { $inc: { statusVersion: 1, draftVersion: 1 } }, { new: true }); if (!updated) throw new ApiError(409, "Publication changed while reordering"); await Promise.all(chapters.map((chapter) => Chapter.updateOne({ _id: chapter._id }, { $set: { order: payload.chapterIds.indexOf(chapter.stableChapterId) + 1000 } }))); await Promise.all(chapters.map((chapter) => Chapter.updateOne({ _id: chapter._id }, { $set: { order: payload.chapterIds.indexOf(chapter.stableChapterId) } }))); await history(updated, "CHAPTERS_REORDERED", publication.status); return updated; }

async function submit(creatorId, id, expectedStatus, action, version) { const publication = await editable(creatorId, id); if (publication.status !== expectedStatus) throw new ApiError(409, `Publication must be ${expectedStatus}`); const chapters = await Chapter.find({ publication: id }).sort({ order: 1 }).lean(); assertCompletePublication(publication, chapters); const snapshot = { version: publication.draftVersion, metadata: metadataSnapshot(publication), chapters: chapters.map(chapterSnapshot), frozenAt: new Date() }; const transitionId = crypto.randomUUID(); const updated = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, status: expectedStatus, statusVersion: version }, { $set: { status: "PENDING_REVIEW", submittedSnapshot: snapshot, submittedVersion: publication.draftVersion, submittedAt: new Date(), creatorVisibleFeedback: "", lastTransitionId: transitionId }, $inc: { statusVersion: 1 } }, { new: true }).select("+submittedSnapshot"); if (!updated) throw new ApiError(409, "Publication changed or was already submitted"); await history(updated, action, expectedStatus, transitionId); return updated; }
export const submitPublication = (creatorId, id, payload) => submit(creatorId, id, "DRAFT", "SUBMITTED", expectedVersion(payload));
export const resubmitPublication = (creatorId, id, payload) => submit(creatorId, id, "CHANGES_REQUESTED", "RESUBMITTED", expectedVersion(payload));
export async function archivePublication(creatorId, id, payload) { ensureId(id); const version = expectedVersion(payload); const current = await Publication.findOne({ _id: id, creator: creatorId }); if (!current) throw new ApiError(404, "Publication not found"); if (!["DRAFT", "CHANGES_REQUESTED", "REJECTED", "PUBLISHED"].includes(current.status)) throw new ApiError(409, "Publication cannot be archived"); const updated = await Publication.findOneAndUpdate({ _id: id, creator: creatorId, status: current.status, statusVersion: version }, { $set: { status: "ARCHIVED", archivedAt: new Date() }, $inc: { statusVersion: 1 } }, { new: true }); if (!updated) throw new ApiError(409, "Publication changed before archive"); await history(updated, "ARCHIVED", current.status); return updated; }
export async function ownerPublication(creatorId, id) { ensureId(id); const publication = await Publication.findOne({ _id: id, creator: creatorId }).select("+submittedSnapshot"); if (!publication) throw new ApiError(404, "Publication not found"); const chapters = await Chapter.find({ publication: id }).sort({ order: 1 }).lean(); return { publication, chapters }; }
