import assert from "node:assert/strict";
import test from "node:test";
import { isPlanetPlacement, isSeenPlacement, serializePublication } from "./publicationAccessService.js";

const chapters = [{ stableChapterId: "one", order: 0, title: "Preview", isPreview: true, blocks: [{ id: "a", type: "TEXT", order: 0, text: "visible" }] }, { stableChapterId: "two", order: 1, title: "Locked", isPreview: false, blocks: [{ id: "b", type: "TEXT", order: 0, text: "secret" }, { id: "m", type: "IMAGE", order: 1, metadata: { label: "Members only", storyPreview: true }, media: { assetId: "secret-asset", mediaType: "IMAGE", resourceType: "image", secureUrl: "https://secret" } }] }];
const record = (kind, status = "PUBLISHED") => ({ _id: "p", creator: "owner", kind, status, publishedAt: new Date(), pricing: {}, publishedSnapshot: { metadata: { title: "Title", summary: "Summary", description: "", category: "", tags: [], pricing: {}, planet: {} }, chapters, version: 1, frozenAt: new Date() } });
test("published Seen returns every chapter publicly while drafts are invisible", () => { assert.equal(serializePublication(record("SEEN"), null).chapters[1].blocks[0].text, "secret"); assert.equal(serializePublication(record("SEEN", "DRAFT"), null), null); });
test("free Worlds are fully open while Premium Planet member chapters stay locked", () => { const world = serializePublication(record("WORLD"), null); assert.equal(world.chapters[1].locked, false); assert.equal(world.chapters[1].blocks[0].text, "secret"); const premium = serializePublication(record("PREMIUM_WORLD"), null); assert.equal(premium.chapters[0].blocks[0].text, "visible"); assert.equal(premium.chapters[1].locked, true); assert.equal(premium.chapters[1].blocks.length, 0); assert.equal(JSON.stringify(premium).includes("secret-asset"), false); });
test("owner and admin receive full authorized snapshots", () => { assert.equal(serializePublication(record("WORLD"), { _id: "owner", role: "creator" }).chapters[1].blocks[0].text, "secret"); assert.equal(serializePublication(record("WORLD"), { _id: "admin", role: "admin" }, { admin: true }).chapters[1].blocks[0].text, "secret"); });
test("subscriber story media is omitted publicly and delivered to active Premium members", () => { const publicView = serializePublication(record("PREMIUM_WORLD"), null); assert.equal(publicView.chapters[1].blocks.length, 0); assert.equal(JSON.stringify(publicView).includes("Members only"), false); const memberView = serializePublication(record("PREMIUM_WORLD"), { _id: "member", role: "fan" }, { entitlement: "ACTIVE_PREMIUM_MEMBER" }); assert.equal(memberView.chapters[1].blocks[1].metadata.storyPreview, true); assert.match(memberView.chapters[1].blocks[1].media.secureUrl, /secret/); });
test("approved free World snapshot stays fully open while a revision is edited or reviewed", () => { for (const status of ["CHANGES_REQUESTED", "PENDING_REVIEW", "REJECTED"]) { const output = serializePublication(record("WORLD", status), null); assert.ok(output); assert.equal(output.chapters[0].blocks[0].text, "visible"); assert.equal(output.chapters[1].locked, false); assert.equal(isPlanetPlacement(record("WORLD", status)), true); } });
test("placement helpers exclude Worlds from Seen feeds", () => { assert.equal(isSeenPlacement(record("SEEN")), true); assert.equal(isSeenPlacement(record("WORLD")), false); assert.equal(isPlanetPlacement(record("WORLD")), true); assert.equal(isPlanetPlacement(record("SEEN")), false); });
