import assert from "node:assert/strict";
import test from "node:test";
import { isPlanetPlacement, isSeenPlacement, serializePublication } from "./publicationAccessService.js";

const chapters = [{ stableChapterId: "one", order: 0, title: "Preview", isPreview: true, blocks: [{ id: "a", type: "TEXT", order: 0, text: "visible" }] }, { stableChapterId: "two", order: 1, title: "Locked", isPreview: false, blocks: [{ id: "b", type: "TEXT", order: 0, text: "secret" }, { id: "m", type: "IMAGE", order: 1, media: { assetId: "secret-asset", mediaType: "IMAGE", resourceType: "image", secureUrl: "https://secret" } }] }];
const record = (kind, status = "PUBLISHED") => ({ _id: "p", creator: "owner", kind, status, publishedAt: new Date(), pricing: {}, publishedSnapshot: { metadata: { title: "Title", summary: "Summary", description: "", category: "", tags: [], pricing: {}, planet: {} }, chapters, version: 1, frozenAt: new Date() } });
test("published Seen returns every chapter publicly while drafts are invisible", () => { assert.equal(serializePublication(record("SEEN"), null).chapters[1].blocks[0].text, "secret"); assert.equal(serializePublication(record("SEEN", "DRAFT"), null), null); });
test("World and Premium public responses hide locked bodies and media", () => { for (const kind of ["WORLD", "PREMIUM_WORLD"]) { const output = serializePublication(record(kind), null); assert.equal(output.chapters[0].blocks[0].text, "visible"); assert.equal(output.chapters[1].locked, true); assert.equal(output.chapters[1].blocks.length, 0); assert.equal(JSON.stringify(output).includes("secret-asset"), false); assert.equal(output.paymentAvailable, false); } });
test("owner and admin receive full authorized snapshots", () => { assert.equal(serializePublication(record("WORLD"), { _id: "owner", role: "creator" }).chapters[1].blocks[0].text, "secret"); assert.equal(serializePublication(record("WORLD"), { _id: "admin", role: "admin" }, { admin: true }).chapters[1].blocks[0].text, "secret"); });
test("placement helpers exclude Worlds from Seen feeds", () => { assert.equal(isSeenPlacement(record("SEEN")), true); assert.equal(isSeenPlacement(record("WORLD")), false); assert.equal(isPlanetPlacement(record("WORLD")), true); assert.equal(isPlanetPlacement(record("SEEN")), false); });
