export const LEDGER_ENTRY_TYPES=["OPENING_BALANCE","CREDIT_ADMIN","CREDIT_TEST","WORLD_PURCHASE_DEBIT","WORLD_CREATOR_EARNING","PREMIUM_JOIN_DEBIT","PREMIUM_CREATOR_EARNING","PREMIUM_RENEWAL_DEBIT","REFUND_CREDIT","CREATOR_EARNING_REVERSAL","MANUAL_ADJUSTMENT"];
export const LEDGER_DIRECTIONS=["CREDIT","DEBIT"];
export const COMMAND_TYPES=["ADMIN_CREDIT","ACTIVATE_WALLET","PURCHASE_WORLD","JOIN_PREMIUM","CANCEL_PREMIUM","RESUME_PREMIUM","RENEW_PREMIUM","REFUND_WORLD","REFUND_PREMIUM"];
export const COMMAND_STATUSES=["PROCESSING","SUCCEEDED","FAILED"];
export const ENTITLEMENT_STATUSES=["ACTIVE","REVOKED","REFUNDED"];
export const MEMBERSHIP_STATUSES=["ACTIVE","CANCEL_AT_PERIOD_END","EXPIRED","CANCELED","SUSPENDED","REFUNDED"];
export const ACTIVE_MEMBERSHIP_STATUSES=["ACTIVE","CANCEL_AT_PERIOD_END"];
export const FINANCIAL_ERROR_CODES={INSUFFICIENT_STARS:"INSUFFICIENT_STARS",CREATOR_REVERSAL_INSUFFICIENT_STARS:"CREATOR_REVERSAL_INSUFFICIENT_STARS",ALREADY_ENTITLED:"ALREADY_ENTITLED",MEMBERSHIP_ALREADY_ACTIVE:"MEMBERSHIP_ALREADY_ACTIVE",IDEMPOTENCY_CONFLICT:"IDEMPOTENCY_CONFLICT",COMMAND_PROCESSING:"COMMAND_PROCESSING",PUBLICATION_NOT_PURCHASABLE:"PUBLICATION_NOT_PURCHASABLE",SELF_PURCHASE_NOT_REQUIRED:"SELF_PURCHASE_NOT_REQUIRED",TRANSACTIONS_REQUIRED:"TRANSACTIONS_REQUIRED",WALLET_UNAVAILABLE:"WALLET_UNAVAILABLE",REFUND_ALREADY_PROCESSED:"REFUND_ALREADY_PROCESSED"};
