import Content from "../models/Content.js"; import ContentReviewHistory from "../models/ContentReviewHistory.js"; import CreatorProfile from "../models/CreatorProfile.js"; import User from "../models/User.js";
import ApiError from "../utils/ApiError.js"; import { asyncHandler } from "../utils/asyncHandler.js"; import { sendResponse } from "../utils/response.js";
import { ACCESS_LEVELS, CONTENT_STATUSES, CONTENT_TYPES } from "../constants/contentConstants.js"; import { serializeContent } from "../services/contentAccessService.js"; import { moderateContent } from "../services/contentModerationService.js";
const paging = (req) => ({ page: Math.max(1, Number(req.query.page) || 1), limit: Math.min(100, Math.max(1, Number(req.query.limit) || 25)) });
export const listModerationContent = asyncHandler(async (req, res) => {
  const { page, limit } = paging(req); const filter = {};
  if (CONTENT_STATUSES.includes(req.query.status)) filter.status = req.query.status; if (CONTENT_TYPES.includes(req.query.contentType)) filter.contentType = req.query.contentType; if (ACCESS_LEVELS.includes(req.query.accessLevel)) filter.accessLevel = req.query.accessLevel;
  if (req.query.creator) { const creatorIds = await User.find({ role: "creator", $or: [{ name: { $regex: String(req.query.creator).trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), $options: "i" } }, { username: { $regex: String(req.query.creator).trim().replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), $options: "i" } }] }).distinct("_id"); filter.creator = { $in: creatorIds }; } if (req.query.category) filter.category = req.query.category; if (req.query.submittedFrom || req.query.submittedTo) filter.submittedAt = { ...(req.query.submittedFrom && { $gte: new Date(req.query.submittedFrom) }), ...(req.query.submittedTo && { $lte: new Date(req.query.submittedTo) }) };
  const sort = req.query.sort === "oldest" ? { submittedAt: 1 } : req.query.sort === "title" ? { title: 1, _id: 1 } : { submittedAt: -1, createdAt: -1 };
  const itemsPromise = req.query.sort === "creator"
    ? Content.aggregate([{ $match: filter }, { $lookup: { from: "users", localField: "creator", foreignField: "_id", as: "creator" } }, { $unwind: { path: "$creator", preserveNullAndEmptyArrays: true } }, { $sort: { "creator.name": 1, _id: 1 } }, { $skip: (page - 1) * limit }, { $limit: limit }])
    : Content.find(filter).select("+internalModerationNote").populate("creator", "name username email avatar").sort(sort).skip((page - 1) * limit).limit(limit).lean();
  const [items, total] = await Promise.all([itemsPromise, Content.countDocuments(filter)]);
  return sendResponse(res, 200, "Moderation content fetched", { items: items.map((item) => serializeContent(item, req.user, { admin: true })), pagination: { page, limit, total, pages: Math.ceil(total / limit) } });
});
async function detail(id, viewer) { const content = await Content.findById(id).select("+internalModerationNote").populate("creator", "name username email avatar status creatorApprovalStatus").populate("reviewedBy", "name username email").lean(); if (!content) throw new ApiError(404, "Content not found"); const [profile, history] = await Promise.all([CreatorProfile.findOne({ user: content.creator._id }).select("bio categories category").lean(), ContentReviewHistory.find({ content: id }).sort({ createdAt: 1 }).populate("admin", "name username email").lean()]); return { content: serializeContent(content, viewer, { admin: true }), creatorProfile: profile, history }; }
export const getModerationContent = asyncHandler(async (req, res) => sendResponse(res, 200, "Moderation detail fetched", await detail(req.params.id, req.user)));
export const getModerationHistory = asyncHandler(async (req, res) => { if (!await Content.exists({ _id: req.params.id })) throw new ApiError(404, "Content not found"); return sendResponse(res, 200, "Moderation history fetched", { history: await ContentReviewHistory.find({ content: req.params.id }).sort({ createdAt: 1 }).populate("admin", "name username email").lean() }); });
const decide = (decision) => asyncHandler(async (req, res) => sendResponse(res, 200, `Content ${decision.toLowerCase()}`, { content: serializeContent(await moderateContent({ id: req.params.id, adminId: req.user._id, decision, review: req.body }), req.user, { admin: true }) }));
export const approveContent = decide("APPROVED"); export const requestContentChanges = decide("CHANGES_REQUESTED"); export const rejectContent = decide("REJECTED");
