import mongoose from "mongoose";
import Story from "../models/Story.js";
import StoryEngagement from "../models/StoryEngagement.js";
import { storeFile, deleteAsset } from "../services/storageService.js";
import ApiError from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { sendResponse } from "../utils/response.js";

const activeStory = async (id) => { if (!mongoose.isValidObjectId(id)) throw new ApiError(400, "Invalid story ID"); const story = await Story.findOne({ _id: id, expiresAt: { $gt: new Date() } }); if (!story) throw new ApiError(404, "Story has expired or is unavailable"); return story; };
const serialize = (story, viewer, engagement) => ({ id: story._id, name: story.creator?.name || "Creator", username: story.creator?.username, avatar: story.creator?.avatar || story.image.url, verified: Boolean(story.creator?.isVerified), image: story.image.url, mediaType: "image", caption: story.caption, createdAt: story.createdAt, expiresAt: story.expiresAt, timeAgo: "Now", isOwn: Boolean(viewer && String(story.creator?._id || story.creator) === String(viewer)), viewed: Boolean(engagement?.viewedAt), viewerReaction: engagement?.reaction || null });
export const createStory = asyncHandler(async (req, res) => { if (!req.file) throw new ApiError(400, "Story image is required"); const caption = String(req.body.caption || "").trim(); if (caption.length > 300) throw new ApiError(400, "Story caption may contain at most 300 characters"); const stored = await storeFile(req.file); const story = await Story.create({ creator: req.user._id, caption, image: { assetId: stored.id, url: stored.url }, expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000) }); await story.populate("creator", "name username avatar isVerified"); return sendResponse(res, 201, "Story is live for 24 hours", { story: serialize(story, req.user._id) }); });
export const listStories = asyncHandler(async (req, res) => { const filter = { expiresAt: { $gt: new Date() }, ...(req.user.role === "creator" ? { creator: req.user._id } : {}) }; const stories = await Story.find(filter).sort({ createdAt: 1 }).populate("creator", "name username avatar isVerified").lean(); const engagements = req.user.role === "fan" ? await StoryEngagement.find({ fan: req.user._id, story: { $in: stories.map((item) => item._id) } }).lean() : []; const byStory = new Map(engagements.map((item) => [String(item.story), item])); return sendResponse(res, 200, "Active stories fetched", stories.map((item) => serialize(item, req.user._id, byStory.get(String(item._id))))); });
export const viewStory = asyncHandler(async (req, res) => { await activeStory(req.params.id); await StoryEngagement.findOneAndUpdate({ story: req.params.id, fan: req.user._id }, { $set: { viewedAt: new Date() } }, { upsert: true, new: true }); return sendResponse(res, 200, "Story viewed", { storyId: req.params.id, viewed: true }); });
export const reactStory = asyncHandler(async (req, res) => { await activeStory(req.params.id); const reaction = String(req.body.reaction || "").trim(); if (!reaction || reaction.length > 12) throw new ApiError(400, "A valid reaction is required"); const engagement = await StoryEngagement.findOneAndUpdate({ story: req.params.id, fan: req.user._id }, { $set: { reaction, viewedAt: new Date() } }, { upsert: true, new: true }); return sendResponse(res, 200, "Reaction sent", { reaction: engagement.reaction, reactedAt: engagement.updatedAt }); });
export const deleteStory = asyncHandler(async (req, res) => { const story = await Story.findOne({ _id: req.params.id, creator: req.user._id }); if (!story) throw new ApiError(404, "Story not found"); await Promise.all([StoryEngagement.deleteMany({ story: story._id }), story.deleteOne()]); await deleteAsset(story.image.assetId).catch(() => {}); return sendResponse(res, 200, "Story deleted"); });
