import mongoose from "mongoose";
import WallPost from "../models/WallPost.js";
import WallEngagement from "../models/WallEngagement.js";
import { storeFile } from "../services/storageService.js";
import ApiError from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { sendResponse } from "../utils/response.js";

const contexts = new Set(["RIGHT_NOW", "COFFEE", "NEED_HELP", "PLACE", "RESTAURANT", "BOOK", "MOVIE", "TRAVEL", "BUSINESS", "FITNESS", "WELLNESS", "LIFESTYLE", "BEAUTY"]);
const serializePost = (post, engagement = {}) => ({ id: post._id, text: post.text, context: post.context, location: post.location, media: post.media || [], createdAt: post.createdAt, creator: { id: post.creator?._id, name: post.creator?.name, username: post.creator?.username, avatar: post.creator?.avatar || "", verified: Boolean(post.creator?.isVerified) }, reactionCount: engagement.reactionCount || 0, commentCount: engagement.commentCount || 0, shareCount: engagement.shareCount || 0, viewerReacted: Boolean(engagement.viewerReacted), viewerShared: Boolean(engagement.viewerShared) });
const requirePost = async (id) => { if (!mongoose.isValidObjectId(id)) throw new ApiError(400, "Invalid Wall post ID"); const post = await WallPost.findOne({ _id: id, status: "PUBLISHED" }); if (!post) throw new ApiError(404, "Wall post not found"); return post; };
const engagementFor = async (post, viewer) => { const id = new mongoose.Types.ObjectId(post); const [counts, mine] = await Promise.all([WallEngagement.aggregate([{ $match: { post: id } }, { $group: { _id: "$type", count: { $sum: 1 } } }]), viewer ? WallEngagement.find({ post, user: viewer, type: { $in: ["REACTION", "SHARE"] } }).lean() : []]); const map = Object.fromEntries(counts.map((item) => [item._id, item.count])); return { reactionCount: map.REACTION || 0, commentCount: map.COMMENT || 0, shareCount: map.SHARE || 0, viewerReacted: mine.some((item) => item.type === "REACTION"), viewerShared: mine.some((item) => item.type === "SHARE") }; };

export const createWallPost = asyncHandler(async (req, res) => { const text = String(req.body.text || "").trim(), context = String(req.body.context || "RIGHT_NOW").toUpperCase(), location = String(req.body.location || "").trim(); if (!text || text.length > 1200) throw new ApiError(400, "Post must contain 1 to 1200 characters"); if (!contexts.has(context)) throw new ApiError(400, "Invalid post context"); const media = req.file ? [await storeFile(req.file)] : []; const post = await WallPost.create({ creator: req.user._id, text, context, location, media: media.map((item) => ({ assetId: item.id, url: item.url })) }); await post.populate("creator", "name username avatar isVerified"); return sendResponse(res, 201, "Wall post published", { post: serializePost(post) }); });
export const listWallPosts = asyncHandler(async (req, res) => { const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 30)); const posts = await WallPost.find({ status: "PUBLISHED" }).sort({ createdAt: -1 }).limit(limit).populate("creator", "name username avatar isVerified").lean(); const items = await Promise.all(posts.map(async (post) => serializePost(post, await engagementFor(post._id, req.user?._id)))); return sendResponse(res, 200, "Wall posts fetched", { items }); });
export const getWallComments = asyncHandler(async (req, res) => { await requirePost(req.params.id); const comments = await WallEngagement.find({ post: req.params.id, type: "COMMENT" }).sort({ createdAt: 1 }).limit(100).populate("user", "name username avatar").lean(); return sendResponse(res, 200, "Wall comments fetched", { comments: comments.map((item) => ({ id: item._id, text: item.text, createdAt: item.createdAt, author: { name: item.user?.name, username: item.user?.username, avatar: item.user?.avatar || "" } })) }); });
export const toggleWallReaction = asyncHandler(async (req, res) => { await requirePost(req.params.id); const filter = { post: req.params.id, user: req.user._id, type: "REACTION" }; const existing = await WallEngagement.findOne(filter); if (existing) await existing.deleteOne(); else await WallEngagement.create(filter); return sendResponse(res, 200, existing ? "Reaction removed" : "Reaction saved", { engagement: await engagementFor(req.params.id, req.user._id) }); });
export const addWallComment = asyncHandler(async (req, res) => { await requirePost(req.params.id); const text = String(req.body.text || "").trim(); if (!text || text.length > 500) throw new ApiError(400, "Comment must contain 1 to 500 characters"); await WallEngagement.create({ post: req.params.id, user: req.user._id, type: "COMMENT", text }); return sendResponse(res, 201, "Comment posted", { engagement: await engagementFor(req.params.id, req.user._id) }); });
export const toggleWallShare = asyncHandler(async (req, res) => { await requirePost(req.params.id); const filter = { post: req.params.id, user: req.user._id, type: "SHARE" }; const existing = await WallEngagement.findOne(filter); if (existing) await existing.deleteOne(); else await WallEngagement.create(filter); return sendResponse(res, 200, existing ? "Post removed from profile" : "Post shared to profile", { engagement: await engagementFor(req.params.id, req.user._id) }); });
