import mongoose from "mongoose";
import WallPost from "../models/WallPost.js";
import WallEngagement, { WALL_REACTIONS } from "../models/WallEngagement.js";
import WallShareEngagement from "../models/WallShareEngagement.js";
import { storeFile } from "../services/storageService.js";
import ApiError from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { sendResponse } from "../utils/response.js";

const contexts = new Set(["RIGHT_NOW", "COFFEE", "NEED_HELP", "PLACE", "RESTAURANT", "BOOK", "MOVIE", "TRAVEL", "BUSINESS", "FITNESS", "WELLNESS", "LIFESTYLE", "BEAUTY"]);
export const serializeWallPost = (post, engagement = {}, activity = {}) => ({ id: activity.feedId || post._id, originalPostId: post._id, shareId: activity.shareId || null, text: post.text, shareCaption: activity.shareCaption || post.shareCaption || "", context: post.context, location: post.location, media: post.media || [], createdAt: post.createdAt, feedCreatedAt: activity.feedCreatedAt || post.createdAt, sharedBy: activity.sharedBy || null, creator: { id: post.creator?._id, name: post.creator?.name, username: post.creator?.username, avatar: post.creator?.avatar || "", verified: Boolean(post.creator?.isVerified) }, reactionCount: engagement.reactionCount || 0, reactionBreakdown: engagement.reactionBreakdown || {}, topReactions: engagement.topReactions || [], viewerReaction: engagement.viewerReaction || null, viewerReacted: Boolean(engagement.viewerReaction || engagement.viewerReacted), commentCount: engagement.commentCount || 0, shareCount: engagement.shareCount || 0, saveCount: engagement.saveCount || 0, viewerShared: Boolean(engagement.viewerShared), viewerSaved: Boolean(engagement.viewerSaved) });
const requirePost = async (id) => { if (!mongoose.isValidObjectId(id)) throw new ApiError(400, "Invalid Wall post ID"); const post = await WallPost.findOne({ _id: id, status: "PUBLISHED" }); if (!post) throw new ApiError(404, "Wall post not found"); return post; };
export const engagementForWallPost = async (post, viewer) => { const id = new mongoose.Types.ObjectId(post); const [counts, reactionCounts, mine] = await Promise.all([WallEngagement.aggregate([{ $match: { post: id } }, { $group: { _id: "$type", count: { $sum: 1 } } }]), WallEngagement.aggregate([{ $match: { post: id, type: "REACTION" } }, { $group: { _id: { $ifNull: ["$reaction", "like"] }, count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } }]), viewer ? WallEngagement.find({ post, user: viewer, type: { $in: ["REACTION", "SHARE", "SAVE"] } }).lean() : []]); const map = Object.fromEntries(counts.map((item) => [item._id, item.count])); const reactionBreakdown = Object.fromEntries(reactionCounts.map((item) => [item._id, item.count])); const viewerReactionRecord = mine.find((item) => item.type === "REACTION"); return { reactionCount: map.REACTION || 0, reactionBreakdown, topReactions: reactionCounts.slice(0, 3).map((item) => item._id), viewerReaction: viewerReactionRecord?.reaction || (viewerReactionRecord ? "like" : null), commentCount: map.COMMENT || 0, shareCount: map.SHARE || 0, saveCount: map.SAVE || 0, viewerShared: mine.some((item) => item.type === "SHARE"), viewerSaved: mine.some((item) => item.type === "SAVE") }; };
const requireShare = async (shareId, postId) => { if (!mongoose.isValidObjectId(shareId)) throw new ApiError(400, "Invalid Wall share ID"); const share = await WallEngagement.findOne({ _id: shareId, post: postId, type: "SHARE" }); if (!share) throw new ApiError(404, "Shared Wall post not found"); return share; };
export const engagementForWallShare = async (share, viewer) => { const id = new mongoose.Types.ObjectId(share); const [counts, reactionCounts, mine] = await Promise.all([WallShareEngagement.aggregate([{ $match: { share: id } }, { $group: { _id: "$type", count: { $sum: 1 } } }]), WallShareEngagement.aggregate([{ $match: { share: id, type: "REACTION" } }, { $group: { _id: "$reaction", count: { $sum: 1 } } }, { $sort: { count: -1, _id: 1 } }]), viewer ? WallShareEngagement.find({ share, user: viewer, type: { $in: ["REACTION", "SAVE"] } }).lean() : []]); const map = Object.fromEntries(counts.map((item) => [item._id, item.count])); const viewerReactionRecord = mine.find((item) => item.type === "REACTION"); return { reactionCount: map.REACTION || 0, reactionBreakdown: Object.fromEntries(reactionCounts.map((item) => [item._id, item.count])), topReactions: reactionCounts.slice(0, 3).map((item) => item._id), viewerReaction: viewerReactionRecord?.reaction || null, commentCount: map.COMMENT || 0, saveCount: map.SAVE || 0, viewerSaved: mine.some((item) => item.type === "SAVE") }; };

export const createWallPost = asyncHandler(async (req, res) => { const text = String(req.body.text || "").trim(), context = String(req.body.context || "RIGHT_NOW").toUpperCase(), location = String(req.body.location || "").trim(); if (!text || text.length > 1200) throw new ApiError(400, "Post must contain 1 to 1200 characters"); if (!contexts.has(context)) throw new ApiError(400, "Invalid post context"); const media = req.file ? [await storeFile(req.file)] : []; const post = await WallPost.create({ creator: req.user._id, text, context, location, media: media.map((item) => ({ assetId: item.id, url: item.url })) }); await post.populate("creator", "name username avatar isVerified"); return sendResponse(res, 201, "Wall post published", { post: serializeWallPost(post) }); });
export const listWallPosts = asyncHandler(async (req, res) => {
  const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 30));
  const [posts, shares] = await Promise.all([
    WallPost.find({ status: "PUBLISHED" }).sort({ createdAt: -1 }).limit(limit).populate("creator", "name username avatar isVerified").lean(),
    WallEngagement.find({ type: "SHARE" }).sort({ createdAt: -1 }).limit(limit).populate("user", "name username avatar isVerified").populate({ path: "post", match: { status: "PUBLISHED" }, populate: { path: "creator", select: "name username avatar isVerified" } }).lean(),
  ]);
  const engagementCache = new Map();
  const engagement = async (postId) => { const key = String(postId); if (!engagementCache.has(key)) engagementCache.set(key, await engagementForWallPost(postId, req.user?._id)); return engagementCache.get(key); };
  const originalItems = await Promise.all(posts.map(async (post) => serializeWallPost(post, await engagement(post._id))));
  const sharedItems = await Promise.all(shares.filter((share) => share.post && share.user).map(async (share) => { const originalEngagement = await engagement(share.post._id); const shareEngagement = await engagementForWallShare(share._id, req.user?._id); return serializeWallPost(share.post, { ...shareEngagement, shareCount: originalEngagement.shareCount, viewerShared: originalEngagement.viewerShared }, { feedId: `share-${share._id}`, shareId: share._id, feedCreatedAt: share.createdAt, shareCaption: share.text || "", sharedBy: { id: share.user._id, name: share.user.name, username: share.user.username, avatar: share.user.avatar || "", verified: Boolean(share.user.isVerified) } }); }));
  const items = [...originalItems, ...sharedItems].sort((left, right) => new Date(right.feedCreatedAt) - new Date(left.feedCreatedAt)).slice(0, limit);
  return sendResponse(res, 200, "Wall posts and shares fetched", { items });
});
export const getWallComments = asyncHandler(async (req, res) => { await requirePost(req.params.id); const shareId = req.query.shareId; if (shareId) await requireShare(shareId, req.params.id); const Model = shareId ? WallShareEngagement : WallEngagement; const scope = shareId ? { share: shareId } : { post: req.params.id }; const comments = await Model.find({ ...scope, type: "COMMENT" }).sort({ createdAt: 1 }).limit(100).populate("user", "name username avatar").lean(); return sendResponse(res, 200, "Wall comments fetched", { comments: comments.map((item) => ({ id: item._id, text: item.text, createdAt: item.createdAt, author: { name: item.user?.name, username: item.user?.username, avatar: item.user?.avatar || "" } })) }); });
export const getWallReactions = asyncHandler(async (req, res) => { await requirePost(req.params.id); const shareId = req.query.shareId; if (shareId) await requireShare(shareId, req.params.id); const Model = shareId ? WallShareEngagement : WallEngagement; const scope = shareId ? { share: new mongoose.Types.ObjectId(shareId) } : { post: new mongoose.Types.ObjectId(req.params.id) }; const [records, grouped] = await Promise.all([Model.find({ ...scope, type: "REACTION" }).sort({ updatedAt: -1 }).limit(500).populate("user", "name username avatar isVerified").lean(), Model.aggregate([{ $match: { ...scope, type: "REACTION" } }, { $group: { _id: { $ifNull: ["$reaction", "like"] }, count: { $sum: 1 } } }])]); const reactions = records.filter((item) => item.user).map((item) => ({ id: item._id, reaction: item.reaction || "like", reactedAt: item.updatedAt || item.createdAt, user: { id: item.user._id, name: item.user.name, username: item.user.username, avatar: item.user.avatar || "", verified: Boolean(item.user.isVerified) } })); const counts = Object.fromEntries(grouped.map((item) => [item._id, item.count])); const total = grouped.reduce((sum, item) => sum + item.count, 0); return sendResponse(res, 200, "Wall reactions fetched", { reactions, counts, total }); });
export const toggleWallReaction = asyncHandler(async (req, res) => { await requirePost(req.params.id); const shareId = req.body.shareId; if (shareId) await requireShare(shareId, req.params.id); const reaction = String(req.body.reaction || "like").toLowerCase(); if (!WALL_REACTIONS.includes(reaction)) throw new ApiError(400, "Invalid Wall reaction"); const Model = shareId ? WallShareEngagement : WallEngagement; const filter = { ...(shareId ? { share: shareId } : { post: req.params.id }), user: req.user._id, type: "REACTION" }; const existing = await Model.findOne(filter); let message = "Reaction saved"; if (existing?.reaction === reaction || (existing && !existing.reaction && reaction === "like")) { await existing.deleteOne(); message = "Reaction removed"; } else if (existing) { existing.reaction = reaction; await existing.save(); message = "Reaction changed"; } else await Model.create({ ...filter, reaction }); return sendResponse(res, 200, message, { engagement: shareId ? await engagementForWallShare(shareId, req.user._id) : await engagementForWallPost(req.params.id, req.user._id) }); });
export const addWallComment = asyncHandler(async (req, res) => { await requirePost(req.params.id); const shareId = req.body.shareId; if (shareId) await requireShare(shareId, req.params.id); const text = String(req.body.text || "").trim(); if (!text || text.length > 500) throw new ApiError(400, "Comment must contain 1 to 500 characters"); const Model = shareId ? WallShareEngagement : WallEngagement; await Model.create({ ...(shareId ? { share: shareId } : { post: req.params.id }), user: req.user._id, type: "COMMENT", text }); return sendResponse(res, 201, "Comment posted", { engagement: shareId ? await engagementForWallShare(shareId, req.user._id) : await engagementForWallPost(req.params.id, req.user._id) }); });
export const toggleWallShare = asyncHandler(async (req, res) => { await requirePost(req.params.id); const filter = { post: req.params.id, user: req.user._id, type: "SHARE" }; const existing = await WallEngagement.findOne(filter); if (existing) { await WallShareEngagement.deleteMany({ share: existing._id }); await existing.deleteOne(); } else { const caption = String(req.body.caption || "").trim(); if (caption.length > 500) throw new ApiError(400, "Share caption must not exceed 500 characters"); await WallEngagement.create({ ...filter, text: caption || undefined }); } return sendResponse(res, 200, existing ? "Post removed from profile" : "Post shared to profile", { engagement: await engagementForWallPost(req.params.id, req.user._id) }); });
export const toggleWallSave = asyncHandler(async (req, res) => { await requirePost(req.params.id); const shareId = req.body.shareId; if (shareId) await requireShare(shareId, req.params.id); const Model = shareId ? WallShareEngagement : WallEngagement; const filter = { ...(shareId ? { share: shareId } : { post: req.params.id }), user: req.user._id, type: "SAVE" }; const existing = await Model.findOne(filter); if (existing) await existing.deleteOne(); else await Model.create(filter); return sendResponse(res, 200, existing ? "Wall post removed from Saved" : "Wall post saved", { engagement: shareId ? await engagementForWallShare(shareId, req.user._id) : await engagementForWallPost(req.params.id, req.user._id) }); });
