import mongoose from "mongoose";
import WallPost from "../models/WallPost.js";
import WallEngagement from "../models/WallEngagement.js";
import { storeFile } from "../services/storageService.js";
import ApiError from "../utils/ApiError.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { sendResponse } from "../utils/response.js";

const contexts = new Set(["RIGHT_NOW", "COFFEE", "NEED_HELP", "PLACE", "RESTAURANT", "BOOK", "MOVIE", "TRAVEL", "BUSINESS", "FITNESS", "WELLNESS", "LIFESTYLE", "BEAUTY"]);
export const serializeWallPost = (post, engagement = {}, activity = {}) => ({ id: activity.feedId || post._id, originalPostId: post._id, text: post.text, shareCaption: activity.shareCaption || post.shareCaption || "", context: post.context, location: post.location, media: post.media || [], createdAt: post.createdAt, feedCreatedAt: activity.feedCreatedAt || post.createdAt, sharedBy: activity.sharedBy || null, creator: { id: post.creator?._id, name: post.creator?.name, username: post.creator?.username, avatar: post.creator?.avatar || "", verified: Boolean(post.creator?.isVerified) }, reactionCount: engagement.reactionCount || 0, commentCount: engagement.commentCount || 0, shareCount: engagement.shareCount || 0, saveCount: engagement.saveCount || 0, viewerReacted: Boolean(engagement.viewerReacted), viewerShared: Boolean(engagement.viewerShared), viewerSaved: Boolean(engagement.viewerSaved) });
const requirePost = async (id) => { if (!mongoose.isValidObjectId(id)) throw new ApiError(400, "Invalid Wall post ID"); const post = await WallPost.findOne({ _id: id, status: "PUBLISHED" }); if (!post) throw new ApiError(404, "Wall post not found"); return post; };
export const engagementForWallPost = async (post, viewer) => { const id = new mongoose.Types.ObjectId(post); const [counts, mine] = await Promise.all([WallEngagement.aggregate([{ $match: { post: id } }, { $group: { _id: "$type", count: { $sum: 1 } } }]), viewer ? WallEngagement.find({ post, user: viewer, type: { $in: ["REACTION", "SHARE", "SAVE"] } }).lean() : []]); const map = Object.fromEntries(counts.map((item) => [item._id, item.count])); return { reactionCount: map.REACTION || 0, commentCount: map.COMMENT || 0, shareCount: map.SHARE || 0, saveCount: map.SAVE || 0, viewerReacted: mine.some((item) => item.type === "REACTION"), viewerShared: mine.some((item) => item.type === "SHARE"), viewerSaved: mine.some((item) => item.type === "SAVE") }; };

export const createWallPost = asyncHandler(async (req, res) => { const text = String(req.body.text || "").trim(), context = String(req.body.context || "RIGHT_NOW").toUpperCase(), location = String(req.body.location || "").trim(); if (!text || text.length > 1200) throw new ApiError(400, "Post must contain 1 to 1200 characters"); if (!contexts.has(context)) throw new ApiError(400, "Invalid post context"); const media = req.file ? [await storeFile(req.file)] : []; const post = await WallPost.create({ creator: req.user._id, text, context, location, media: media.map((item) => ({ assetId: item.id, url: item.url })) }); await post.populate("creator", "name username avatar isVerified"); return sendResponse(res, 201, "Wall post published", { post: serializeWallPost(post) }); });
export const listWallPosts = asyncHandler(async (req, res) => {
  const limit = Math.min(50, Math.max(1, Number(req.query.limit) || 30));
  const [posts, shares] = await Promise.all([
    WallPost.find({ status: "PUBLISHED" }).sort({ createdAt: -1 }).limit(limit).populate("creator", "name username avatar isVerified").lean(),
    WallEngagement.find({ type: "SHARE" }).sort({ createdAt: -1 }).limit(limit).populate("user", "name username avatar isVerified").populate({ path: "post", match: { status: "PUBLISHED" }, populate: { path: "creator", select: "name username avatar isVerified" } }).lean(),
  ]);
  const engagementCache = new Map();
  const engagement = async (postId) => { const key = String(postId); if (!engagementCache.has(key)) engagementCache.set(key, await engagementForWallPost(postId, req.user?._id)); return engagementCache.get(key); };
  const originalItems = await Promise.all(posts.map(async (post) => serializeWallPost(post, await engagement(post._id))));
  const sharedItems = await Promise.all(shares.filter((share) => share.post && share.user).map(async (share) => serializeWallPost(share.post, await engagement(share.post._id), { feedId: `share-${share._id}`, feedCreatedAt: share.createdAt, shareCaption: share.text || "", sharedBy: { id: share.user._id, name: share.user.name, username: share.user.username, avatar: share.user.avatar || "", verified: Boolean(share.user.isVerified) } })));
  const items = [...originalItems, ...sharedItems].sort((left, right) => new Date(right.feedCreatedAt) - new Date(left.feedCreatedAt)).slice(0, limit);
  return sendResponse(res, 200, "Wall posts and shares fetched", { items });
});
export const getWallComments = asyncHandler(async (req, res) => { await requirePost(req.params.id); const comments = await WallEngagement.find({ post: req.params.id, type: "COMMENT" }).sort({ createdAt: 1 }).limit(100).populate("user", "name username avatar").lean(); return sendResponse(res, 200, "Wall comments fetched", { comments: comments.map((item) => ({ id: item._id, text: item.text, createdAt: item.createdAt, author: { name: item.user?.name, username: item.user?.username, avatar: item.user?.avatar || "" } })) }); });
export const toggleWallReaction = asyncHandler(async (req, res) => { await requirePost(req.params.id); const filter = { post: req.params.id, user: req.user._id, type: "REACTION" }; const existing = await WallEngagement.findOne(filter); if (existing) await existing.deleteOne(); else await WallEngagement.create(filter); return sendResponse(res, 200, existing ? "Reaction removed" : "Reaction saved", { engagement: await engagementForWallPost(req.params.id, req.user._id) }); });
export const addWallComment = asyncHandler(async (req, res) => { await requirePost(req.params.id); const text = String(req.body.text || "").trim(); if (!text || text.length > 500) throw new ApiError(400, "Comment must contain 1 to 500 characters"); await WallEngagement.create({ post: req.params.id, user: req.user._id, type: "COMMENT", text }); return sendResponse(res, 201, "Comment posted", { engagement: await engagementForWallPost(req.params.id, req.user._id) }); });
export const toggleWallShare = asyncHandler(async (req, res) => { await requirePost(req.params.id); const filter = { post: req.params.id, user: req.user._id, type: "SHARE" }; const existing = await WallEngagement.findOne(filter); if (existing) await existing.deleteOne(); else { const caption = String(req.body.caption || "").trim(); if (caption.length > 500) throw new ApiError(400, "Share caption must not exceed 500 characters"); await WallEngagement.create({ ...filter, text: caption || undefined }); } return sendResponse(res, 200, existing ? "Post removed from profile" : "Post shared to profile", { engagement: await engagementForWallPost(req.params.id, req.user._id) }); });
export const toggleWallSave = asyncHandler(async (req, res) => { await requirePost(req.params.id); const filter = { post: req.params.id, user: req.user._id, type: "SAVE" }; const existing = await WallEngagement.findOne(filter); if (existing) await existing.deleteOne(); else await WallEngagement.create(filter); return sendResponse(res, 200, existing ? "Wall post removed from Saved" : "Wall post saved", { engagement: await engagementForWallPost(req.params.id, req.user._id) }); });
